version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    command: sh ./entrypoint.sh
    container_name: backend
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - SQL_PASSWORD=${PG_PASSWORD}
      - SQL_USER=${PG_USER}
      - SQL_DATABASE=${PG_DATABASE}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    expose:
      - 8000
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: "yarn start"
    container_name: frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 3000
    volumes:
      - './frontend:/app'
      - /app/node_modules

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    logging:
      driver: none

volumes:
  static_volume:
  media_volume: