# Generated by Django 3.0.3 on 2020-02-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200224_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='is trainer?'),
        ),
    ]
